In [3]:
import re
import pandas as pd

In [49]:
def extract_gender(biography, name):
    if not biography or pd.isna(biography):
        return "Unknown"
    
    bio_lower = biography.lower()
    
    # check for explicit gender statement first
    if re.search(r'gender:\s*male', bio_lower):
        return "Male"
    if re.search(r'gender:\s*female', bio_lower):
        return "Female"
    
    # otherwise, count pronouns
    male_pronouns = len(re.findall(r'\b(he|him|his)\b', bio_lower))
    female_pronouns = len(re.findall(r'\b(she|her|hers)\b', bio_lower))
    
    if male_pronouns > female_pronouns:
        return "Male"
    elif female_pronouns > male_pronouns:
        return "Female"
    
    return "Unknown"

In [65]:
# Test it
results_df = pd.read_csv("character_bios_final.csv")

results_df["gender"] = results_df.apply(
    lambda row: extract_gender(row["biography"], row["name"]), axis=1
)

In [53]:
!pip install nltk

Requirement already satisfied: nltk in /Users/marianama/anaconda3/lib/python3.11/site-packages (3.8.1)
Requirement already satisfied: click in /Users/marianama/anaconda3/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /Users/marianama/anaconda3/lib/python3.11/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/marianama/anaconda3/lib/python3.11/site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in /Users/marianama/anaconda3/lib/python3.11/site-packages (from nltk) (4.65.0)

In [66]:
results_df.head(5)

,character_id,mal_id,name,biography,gender
0,7,672.0,Gintoki Sakata,"Age: 27, 29 (2 years arc)\nBirthday: October 1...",Male
1,10,286647.0,Kagura,NaN,Unknown
2,12,673.0,Shinpachi Shimura,Birthdate: August 12\nZodiac: Leo\nHeight: 166...,Male
3,14,1533.0,Kotarou Katsura,Age: 20s\nBirthday: June 26 (Cancer)\nHeight: ...,Male
4,16,2650.0,Toushirou Hijikata,Species: Human\nGender: Male\nBirthday: May 5 ...,Male

In [54]:
# use nltk to extract adjectives from characters' bios to get list of personality traits
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk import pos_tag, word_tokenize
from collections import Counter

def extract_adjectives(biography):
    if not biography or pd.isna(biography):
        return []
    tokens = word_tokenize(biography)
    tagged = pos_tag(tokens)
    adjectives = [word.lower() for word, tag in tagged 
                  if tag in ("JJ", "JJR", "JJS")
                  and len(word) > 2]
    return list(set(adjectives))

# Test on a few first
for _, row in results_df.head(10).iterrows():
    adjs = extract_adjectives(row["biography"])
    print(f"{row['name']}: {adjs}\n")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/marianama/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to /Users/marianama/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/marianama/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Gintoki Sakata: ['most', 'latest', 'such', 'reckless', 'impressive', 'oppressive', 'dentist', 'other', 'old', 'second', 'fearsome', 'odd', 'several', 'great', 'unmatched', 'pachinko', 'jump', 'sweet', 'only', 'big', 'similar', 'initial', 'due', 'major', 'white', 'famous', 'female']

Kagura: []

Shinpachi Shimura: ['competent', 'comedian', '21-22', 'meek', 'leo', 'spilled']

Kotarou Katsura: ['japanese', 'such', 'first', 'left', 'violent', 'wanted', 'other', 'historical', 'important', 'odd', 'outdated', 'dramatic', 'skull', 'past', 'right', 'uncanny', 'similar', 'initial', 'metallic', 'due', 'subsequent', 'former', 'same', 'terrorist', 'complete', 'english']

Toushirou Hijikata: ['right-handed', 'such', 'rival', 'hot-tempered', 'taurus', 'cold', 'famed', 'trouble-maker', 'demonic', 'close', 'popular', 'loyal', 'fearsome', 'constant', 'emotional', 'male', 'compassionate', 'big', 'many', 'human', 'disciplinary', 'good']

Sougo Okita: ['sakura-blossom', 'japanese', 'original', 'unfinished', 'legal', '~desaa', 'other', 'second', 'distinctive', 'historical', 'little', 'frequent', 'hilarious', 'deadpan', 'great', 'childish', '2nd', 'only', 'best', 'ugly', 'light-hearted', 'female']

Shinsuke Takasugi: ['first', 'left', 'radical', 'unclear', 'post-joui', 'latter', 'large-scale', 'elementary', 'dangerous', 'historical', 'considerable', 'nihilistic', 'rotten', 'insight', 'least', 'recognizable', 'only', 'colorful', 'many', 'due', 'major', 'main', 'purple', 'former', 'same', 'terrorist']

Taizou Hasegawa: ['successful', 'most', 'free', 'old', 'official', 'dignitary', 'various', 'unfavourable', 'short', 'middle-aged', 'half-moon', 'part-time', 'odd', 'superior', 'marude', 'decent', 'useless', 'jobless', 'only', 'best', 'due', 'unfortunate', 'new', 'good']

Tsukuyo: ['heartless', 'blonde-haired', 'better', 'original', 'older', 'perfect', 'fake', 'underground', 'difficult', 'precious', 'own']

Kamui: []

In [55]:
from collections import Counter

# extract adjectives from all bios
results_df["all_adjectives"] = results_df["biography"].apply(extract_adjectives)

# get most common across entire dataset
all_adj = []
for adjs in results_df["all_adjectives"].dropna():
    all_adj.extend(adjs)

top_adj = Counter(all_adj).most_common(500)
for adj, count in top_adj:
    print(f"{adj}: {count}")

KeyboardInterrupt:

In [56]:
# personality adjectives from the list
personality_adjectives = {
    # stereotypically "positive" traits
    "friendly", "cheerful", "kind-hearted", "gentle", "calm", "loyal", "polite", "nice", "kind",
    "honest", "confident", "energetic", "optimistic", "playful", "carefree",
    "innocent", "humble", "reliable", "responsible", "caring", "supportive",
    "helpful", "determined", "passionate", "enthusiastic", "outgoing", "charismatic",
    "mature", "independent", "perceptive", "observant", "thoughtful", "logical",
    "intelligent", "smart", "bright", "capable", "talented", "athletic", "skilled",
    "cool", "elegant", "noble", "protective", "peaceful", "powerful", "pure", "good-natured",
    "popular", "beautiful", "sweet", "sharp", "innocent", "attractive", "talented", "playful",
    "level-headed", "soft-spoken", "strong-willed", "strong", "laid-back", "easygoing", "mature", 
    "successful", "charismatic", "curious", "trusted", "knowledgeable",
    
    # stereotypically "negative" traits
    "arrogant", "selfish", "shy", "timid", "lazy", "naive", "clumsy", "competitive",
    "stubborn", "aggressive", "violent", "cruel", "ruthless", "manipulative",
    "sadistic", "jealous", "childish", "reckless", "impulsive", "perverted",
    "eccentric", "weird", "obsessive", "cynical", "sarcastic", "aloof", 
    "stoic", "serious", "strict", "harsh", "rude", "rebellious", "competitive",
    "proud", "cowardly", "nervous", "awkward", "sensitive", "emotional", "dramatic",
    "mischievous", "wild", "crazy", "mad", "hostile", "fierce", "brutal",
    "mysterious", "secretive", "reserved", "introverted", "tomboyish", "timid",
    "short-tempered", "tsundere", "oblivious", "cautious", "suspicious", "sensitive",
    "reluctant", "loud", "talkative", "bold", "blunt", "direct", "weak", "angry", "oblivious"
}

In [57]:
# Function to extract specified traits from each character's biography
def extract_personality_traits(biography):
    if not biography or pd.isna(biography):
        return []
    
    bio_lower = biography.lower()
    return [trait for trait in personality_adjectives 
            if re.search(rf'\b{trait}\b', bio_lower)]

# Apply to dataset
results_df["personality_traits"] = results_df["biography"].apply(extract_personality_traits)

# Check results
for _, row in results_df.head(10).iterrows():
    print(f"{row['name']}: {row['personality_traits']}")

# See how many characters have at least one trait
has_traits = results_df["personality_traits"].apply(len) > 0
print(f"\nCharacters with at least one trait: {has_traits.sum()} ({has_traits.mean():.1%})")

Gintoki Sakata: ['reckless', 'sweet']
Kagura: []
Shinpachi Shimura: []
Kotarou Katsura: ['violent', 'dramatic']
Toushirou Hijikata: ['loyal', 'emotional', 'popular']
Sougo Okita: ['childish']
Shinsuke Takasugi: ['skilled']
Taizou Hasegawa: ['successful']
Tsukuyo: ['ruthless']
Kamui: []

Characters with at least one trait: 4789 (37.5%)

In [59]:
# Test on specific character to see output
bio = results_df[results_df["mal_id"] == 155904.0]["biography"].values[0]
print(bio)
print(extract_personality_traits(bio))

Age: 17
Birth place: Rokushoukan
Hair color: Black (WN), Dark Green (LN)
Eye color: (Black (WN), Purple (LN)
Height: 153 cm (5'0")

Maomao became a maidservant to the Emperor's harem after being kidnapped and sold. She used to live with her father as a pharmacist in the red light district and is very knowledgeable about medicine and poisons but isn't very interested in other humans.

She is skinny and short, and her plain face is covered with freckles.

AbilitiesMaomao's name is derived from 猫 (māo), the Chinese word for cat. This reinforces the fact that she is often described as a cat or cat-like.


(Source: The Apothecary Diaries Wiki, edited)
['knowledgeable']

In [60]:
# Now check bias / ratio of female to male personalitys extracted
results_df["has_traits"] = results_df["personality_traits"].apply(len) > 0

print("Trait extraction rate by gender:")
print(results_df.groupby("gender")["has_traits"].mean())

print("\nGender distribution overall:")
print(results_df["gender"].value_counts())

Trait extraction rate by gender:
gender
Female     0.558942
Male       0.549083
Unknown    0.046089
Name: has_traits, dtype: float64

Gender distribution overall:
gender
Unknown    4513
Female     4233
Male       4034
Name: count, dtype: int64

In [62]:
print(results_df[results_df["name"] == "Tooru Honda"]["personality_traits"].values[0])

['optimistic', 'polite', 'kind']

In [63]:
# Save results to csv
results_df.to_csv("character_personalities_final.csv", index=False)

In [64]:
results_df.sample(50)

,character_id,mal_id,name,biography,gender,personality_traits,has_traits
7741,20791,215857.0,Katori-kun,Occupation: Sales department\nSpecies: Human-P...,Male,[cool],True
5421,8872,110899.0,Ikuya Kirishima,Ikuya Kirishima was the first-year junior high...,Male,[],False
4961,12152,11771.0,Arslan,"Age: 11, 14 (post time-skip)\nBirthday: May 23...",Male,"[intelligent, charismatic]",True
581,1463,111245.0,Rudeus Greyrat,Rudeus Greyrat is a reincarnated NEET who died...,Male,[],False
11802,42447,142394.0,Niwatori,NaN,Unknown,[],False
9485,27871,128504.0,Mugi Awaya,Another high school student who is in love wit...,Unknown,[],False
2331,5238,172491.0,Midori Asakusa,"Asakusa is a freshman at Shibahama Highschool,...",Female,[],False
5115,12511,274448.0,Hosaka,NaN,Unknown,[],False
8940,25586,90169.0,Minori Koganuma,A well-endowed member of the JSDF assigned to ...,Unknown,[skilled],True
7445,19573,151107.0,Nagahide Niwa,NaN,Unknown,[],False
5830,14526,281799.0,Ginji,NaN,Unknown,[],False
6475,16734,51587.0,Naoya Teshigawara,"Teshigawara is the class' ""mood maker.""\n\nHe ...",Male,[],False
631,1560,71267.0,Kenma Kozume,Team: Nekoma High School\nAge: 16\nHeight: 169...,Male,"[cool, skilled, reserved]",True
3316,3979,4713.0,Syaoran Li,Mysterious person kept asleep in a liquid cham...,Male,[mysterious],True
7623,20410,223790.0,Dialga,"Dialga is a dark-blue, sauropod-like Pokémon w...",Unknown,"[capable, noble, protective, violent, powerful]",True
272,708,282342.0,Björn,NaN,Unknown,[],False
8466,23661,254901.0,Rimu,Lyn is a character of the day who appeared in ...,Female,[caring],True
1025,2366,8945.0,Noriaki Kakyouin,Age: 17\nGender: Male\nBlood Type: A\nHeight: ...,Male,[calm],True
1476,3498,196615.0,"Amati, Fermi",NaN,Unknown,[],False
10725,34606,144285.0,Ono,One of the main characters of the second side ...,Male,[],False
10115,31351,193229.0,Cayna,Real name: Keina Kagami (各務 桂菜)\n\nWhen she wa...,Female,[],False
7304,19144,284513.0,Math Teacher,NaN,Unknown,[],False
12428,48257,199426.0,Beach,NaN,Unknown,[],False
4916,12083,126020.0,Mitsuya Takanashi,NaN,Unknown,[],False
7005,18359,11164.0,Naoki Irie,Birthday: November 12\n\nThe male lead of the ...,Male,[smart],True
10939,36172,197685.0,Tanta,"Tanta is the son of Gonzo's sister, Nao, and h...",Male,[],False
2161,4884,91371.0,Kyousuke Hori,Kyousuke is Kyouko's father who is often not h...,Male,[supportive],True
4656,11186,7422.0,Cat King,The Cat King is fat and deranged and is instan...,Female,"[protective, oblivious]",True
785,1886,409.0,Nagamitsu Sakonshougen,Nagamitsu Sakonshougen is a man who believes h...,Male,[],False
8511,23867,87877.0,Shuka Karino,Age: 16\nBirthday: March 26\nSigil: Queen of T...,Female,"[skilled, powerful]",True
6422,16600,171196.0,Masatsugu Nakamura,Masamichi's only son. He is an 11-year-old fif...,Male,[],False
7425,19528,224058.0,Kakinuma,NaN,Unknown,[],False
5293,12989,19984.0,Dakuan,Dakuwan is a spy for the Tokugawa clan who is ...,Male,[sadistic],True
12105,25720,200182.0,Sibylla,NaN,Unknown,[],False
3463,7980,75412.0,Mamedai Kitashirakawa,Tamako's father who runs the family's mochi shop.,Unknown,[],False
1643,3862,171313.0,Nagi Amano,Amano Nagi is the younger brother of Amano Hin...,Male,[],False
10235,32142,160743.0,Lily Amane,NaN,Unknown,[],False
1833,4222,131895.0,Orga Itsuka,"Orga is a leader among the boys of CGS, later ...",Male,"[capable, trusted]",True
6667,17143,197554.0,Hana Sunomiya,She is a high school student who joined the ar...,Female,[],False
11512,37165,165131.0,Takuya Arima,Takuya Arima is a third-year student at Sakaim...,Male,[],False
9761,18208,3111.0,Masaru Katou,Age: 17\nHeight: 192 cm\n\nMasaru Katou has a ...,Male,"[protective, responsible]",True
10639,34288,85577.0,Kyoutarou Kakei,Height: 174cm\nBirthday: April 28\nFavorite co...,Male,[],False
1924,4407,224301.0,Shou Adachi,NaN,Unknown,[],False
2246,5052,148226.0,Princess Daruma,NaN,Unknown,[],False
10382,32755,75772.0,Kaoru Asoi,Eita's classmate and his best friend.\n\nHe is...,Male,[],False
5528,13631,268663.0,Pegbar,NaN,Unknown,[],False
11428,36988,143743.0,Katalina Alize,Age: 24\nHeight: 169 cm\nRace: Human\nHobbies:...,Female,"[trusted, skilled]",True
2630,5937,287402.0,Otto,NaN,Unknown,[],False
9673,18308,260217.0,Chloe Welter,NaN,Unknown,[],False
5928,14857,140412.0,Yuusuke Yagi,Kouhei's friend since high school and childhoo...,Male,[],False

In [67]:
import pandas as pd
import ast
from collections import Counter

chars = pd.read_csv("../cleaned_data/character_personalities_final.csv")

def parse_traits(x):
    if pd.isna(x) or x == "[]" or x == "":
        return []
    try:
        return ast.literal_eval(x)
    except:
        return []

chars["traits_list"] = chars["personality_traits"].apply(parse_traits)

valid = chars[chars["gender"].isin(["Male", "Female"])].copy()
male_total = (valid["gender"] == "Male").sum()
female_total = (valid["gender"] == "Female").sum()

male_counts = Counter()
female_counts = Counter()

for _, row in valid.iterrows():
    if row["gender"] == "Male":
        male_counts.update(row["traits_list"])
    else:
        female_counts.update(row["traits_list"])

all_traits = set(male_counts.keys()) | set(female_counts.keys())

rows = []
for trait in all_traits:
    m = male_counts[trait]
    f = female_counts[trait]
    total = m + f
    rows.append({
        "trait": trait,
        "male_count": m,
        "female_count": f,
        "total": total,
        "male_pct": round(m / male_total * 100, 1),
        "female_pct": round(f / female_total * 100, 1),
        "female_share": round(f / total * 100, 1) if total > 0 else 0
    })

trait_df = pd.DataFrame(rows).sort_values("total", ascending=False)

# Display with all columns visible
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 10)
pd.set_option("display.width", 120)

print(trait_df[trait_df["total"] >= 20].to_string(index=False))

         trait  male_count  female_count  total  male_pct  female_pct  female_share
        strong         261           242    503       6.5         5.7          48.1
          kind         213           246    459       5.3         5.8          53.6
      powerful         185           111    296       4.6         2.6          37.5
       skilled         149            99    248       3.7         2.3          39.9
       popular         116           125    241       2.9         3.0          51.9
       serious         149            92    241       3.7         2.2          38.2
          calm         145            87    232       3.6         2.1          37.5
     beautiful          60           169    229       1.5         4.0          73.8
           shy          59           168    227       1.5         4.0          74.0
       capable         104           103    207       2.6         2.4          49.8
      friendly         100           104    204       2.5         2.5          51.0
    mysterious         101            99    200       2.5         2.3          49.5
        caring          75           106    181       1.9         2.5          58.6
      cheerful          56           123    179       1.4         2.9          68.7
          weak          86            66    152       2.1         1.6          43.4
         loyal         103            46    149       2.6         1.1          30.9
   intelligent          76            65    141       1.9         1.5          46.1
        gentle          64            64    128       1.6         1.5          50.0
   responsible          69            58    127       1.7         1.4          45.7
         sweet          39            87    126       1.0         2.1          69.0
          cool          75            49    124       1.9         1.2          39.5
        mature          35            84    119       0.9         2.0          70.6
      childish          41            76    117       1.0         1.8          65.0
     energetic          33            83    116       0.8         2.0          71.6
       jealous          41            75    116       1.0         1.8          64.7
        bright          43            72    115       1.1         1.7          62.6
      talented          62            47    109       1.5         1.1          43.1
     confident          46            60    106       1.1         1.4          56.6
         angry          50            53    103       1.2         1.3          51.5
        polite          49            53    102       1.2         1.3          52.0
     perverted          59            40     99       1.5         0.9          40.4
      arrogant          62            31     93       1.5         0.7          33.3
        strict          35            57     92       0.9         1.3          62.0
         noble          47            44     91       1.2         1.0          48.4
    protective          55            36     91       1.4         0.9          39.6
     emotional          46            41     87       1.1         1.0          47.1
         sharp          35            49     84       0.9         1.2          58.3
         smart          42            41     83       1.0         1.0          49.4
       violent          37            46     83       0.9         1.1          55.4
      innocent          25            56     81       0.6         1.3          69.1
    determined          36            43     79       0.9         1.0          54.4
         proud          32            45     77       0.8         1.1          58.4
        clumsy          15            61     76       0.4         1.4          80.3
      sadistic          33            42     75       0.8         1.0          56.0
        honest          35            39     74       0.9         0.9          52.7
          pure          30            43     73       0.7         1.0          58.9
     sensitive          29            43     72       0.7         1.0          59.7
      reserved          34            35     69       0.8         0.8          50.7
         timid          19            50     69       0.5         1.2          72.5
      athletic          26            41     67       0.6         1.0          61.2
      carefree          42            25     67       1.0         0.6          37.3
          nice          35            29     64       0.9         0.7          45.3
    attractive          20            41     61       0.5         1.0          67.2
         cruel          35            25     60       0.9         0.6          41.7
      tsundere           7            53     60       0.2         1.3          88.3
          lazy          34            25     59       0.8         0.6          42.4
         blunt          29            30     59       0.7         0.7          50.8
   independent          15            44     59       0.4         1.0          74.6
      outgoing          20            39     59       0.5         0.9          66.1
      stubborn          24            35     59       0.6         0.8          59.3
         harsh          27            30     57       0.7         0.7          52.6
         naive          29            25     54       0.7         0.6          46.3
        direct          38            16     54       0.9         0.4          29.6
      ruthless          36            18     54       0.9         0.4          33.3
    aggressive          24            29     53       0.6         0.7          54.7
       playful          23            30     53       0.6         0.7          56.6
     eccentric          36            16     52       0.9         0.4          30.8
          wild          32            19     51       0.8         0.4          37.3
         stoic          28            22     50       0.7         0.5          44.0
    passionate          26            23     49       0.6         0.5          46.9
          rude          31            17     48       0.8         0.4          35.4
          loud          24            22     46       0.6         0.5          47.8
         aloof          23            23     46       0.6         0.5          50.0
    optimistic          19            26     45       0.5         0.6          57.8
      reliable          24            20     44       0.6         0.5          45.5
       selfish          26            18     44       0.6         0.4          40.9
    successful          31            12     43       0.8         0.3          27.9
   charismatic          30            12     42       0.7         0.3          28.6
 knowledgeable          21            21     42       0.5         0.5          50.0
           mad          25            15     40       0.6         0.4          37.5
   mischievous          14            25     39       0.3         0.6          64.1
       awkward          24            14     38       0.6         0.3          36.8
  kind-hearted          17            21     38       0.4         0.5          55.3
   competitive          15            22     37       0.4         0.5          59.5
       curious          15            22     37       0.4         0.5          59.5
     sarcastic          17            20     37       0.4         0.5          54.1
       elegant           8            28     36       0.2         0.7          77.8
       helpful          18            18     36       0.4         0.4          50.0
     oblivious          22            13     35       0.5         0.3          37.1
     impulsive          22            13     35       0.5         0.3          37.1
         crazy          19            15     34       0.5         0.4          44.1
    perceptive          17            17     34       0.4         0.4          50.0
        humble          18            16     34       0.4         0.4          47.1
 strong-willed          12            22     34       0.3         0.5          64.7
      peaceful          21            12     33       0.5         0.3          36.4
         weird          14            19     33       0.3         0.4          57.6
  manipulative          13            20     33       0.3         0.5          60.6
     easygoing          25             8     33       0.6         0.2          24.2
       trusted          23            10     33       0.6         0.2          30.3
     tomboyish           3            29     32       0.1         0.7          90.6
       nervous          14            18     32       0.3         0.4          56.2
        fierce          18            14     32       0.4         0.3          43.8
  enthusiastic          19            13     32       0.5         0.3          40.6
        brutal          16            15     31       0.4         0.4          48.4
    supportive          17            14     31       0.4         0.3          45.2
   soft-spoken           8            22     30       0.2         0.5          73.3
     obsessive          12            17     29       0.3         0.4          58.6
          bold           9            19     28       0.2         0.4          67.9
      reckless          18            10     28       0.4         0.2          35.7
       cynical          19             8     27       0.5         0.2          29.6
     observant          17            10     27       0.4         0.2          37.0
    thoughtful          17            10     27       0.4         0.2          37.0
   introverted          12            15     27       0.3         0.4          55.6
     laid-back          18             9     27       0.4         0.2          33.3
       logical          18             8     26       0.4         0.2          30.8
    rebellious          11            15     26       0.3         0.4          57.7
       hostile           9            17     26       0.2         0.4          65.4
     reluctant          13            12     25       0.3         0.3          48.0
    suspicious          12            12     24       0.3         0.3          50.0
  good-natured          16             8     24       0.4         0.2          33.3
short-tempered          14             9     23       0.3         0.2          39.1
  level-headed          14             8     22       0.3         0.2          36.4
     talkative          12             9     21       0.3         0.2          42.9
      cowardly          16             4     20       0.4         0.1          20.0

In [69]:
trait_df = pd.DataFrame(rows).sort_values("female_share", ascending=False)

# Display with all columns visible
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 10)
pd.set_option("display.width", 120)

print(trait_df[trait_df["total"] >= 20].to_string(index=False))

         trait  male_count  female_count  total  male_pct  female_pct  female_share
     tomboyish           3            29     32       0.1         0.7          90.6
      tsundere           7            53     60       0.2         1.3          88.3
        clumsy          15            61     76       0.4         1.4          80.3
       elegant           8            28     36       0.2         0.7          77.8
   independent          15            44     59       0.4         1.0          74.6
           shy          59           168    227       1.5         4.0          74.0
     beautiful          60           169    229       1.5         4.0          73.8
   soft-spoken           8            22     30       0.2         0.5          73.3
         timid          19            50     69       0.5         1.2          72.5
     energetic          33            83    116       0.8         2.0          71.6
        mature          35            84    119       0.9         2.0          70.6
      innocent          25            56     81       0.6         1.3          69.1
         sweet          39            87    126       1.0         2.1          69.0
      cheerful          56           123    179       1.4         2.9          68.7
          bold           9            19     28       0.2         0.4          67.9
    attractive          20            41     61       0.5         1.0          67.2
      outgoing          20            39     59       0.5         0.9          66.1
       hostile           9            17     26       0.2         0.4          65.4
      childish          41            76    117       1.0         1.8          65.0
       jealous          41            75    116       1.0         1.8          64.7
 strong-willed          12            22     34       0.3         0.5          64.7
   mischievous          14            25     39       0.3         0.6          64.1
        bright          43            72    115       1.1         1.7          62.6
        strict          35            57     92       0.9         1.3          62.0
      athletic          26            41     67       0.6         1.0          61.2
  manipulative          13            20     33       0.3         0.5          60.6
     sensitive          29            43     72       0.7         1.0          59.7
       curious          15            22     37       0.4         0.5          59.5
   competitive          15            22     37       0.4         0.5          59.5
      stubborn          24            35     59       0.6         0.8          59.3
          pure          30            43     73       0.7         1.0          58.9
     obsessive          12            17     29       0.3         0.4          58.6
        caring          75           106    181       1.9         2.5          58.6
         proud          32            45     77       0.8         1.1          58.4
         sharp          35            49     84       0.9         1.2          58.3
    optimistic          19            26     45       0.5         0.6          57.8
    rebellious          11            15     26       0.3         0.4          57.7
         weird          14            19     33       0.3         0.4          57.6
       playful          23            30     53       0.6         0.7          56.6
     confident          46            60    106       1.1         1.4          56.6
       nervous          14            18     32       0.3         0.4          56.2
      sadistic          33            42     75       0.8         1.0          56.0
   introverted          12            15     27       0.3         0.4          55.6
       violent          37            46     83       0.9         1.1          55.4
  kind-hearted          17            21     38       0.4         0.5          55.3
    aggressive          24            29     53       0.6         0.7          54.7
    determined          36            43     79       0.9         1.0          54.4
     sarcastic          17            20     37       0.4         0.5          54.1
          kind         213           246    459       5.3         5.8          53.6
        honest          35            39     74       0.9         0.9          52.7
         harsh          27            30     57       0.7         0.7          52.6
        polite          49            53    102       1.2         1.3          52.0
       popular         116           125    241       2.9         3.0          51.9
         angry          50            53    103       1.2         1.3          51.5
      friendly         100           104    204       2.5         2.5          51.0
         blunt          29            30     59       0.7         0.7          50.8
      reserved          34            35     69       0.8         0.8          50.7
       helpful          18            18     36       0.4         0.4          50.0
         aloof          23            23     46       0.6         0.5          50.0
        gentle          64            64    128       1.6         1.5          50.0
 knowledgeable          21            21     42       0.5         0.5          50.0
    suspicious          12            12     24       0.3         0.3          50.0
    perceptive          17            17     34       0.4         0.4          50.0
       capable         104           103    207       2.6         2.4          49.8
    mysterious         101            99    200       2.5         2.3          49.5
         smart          42            41     83       1.0         1.0          49.4
         noble          47            44     91       1.2         1.0          48.4
        brutal          16            15     31       0.4         0.4          48.4
        strong         261           242    503       6.5         5.7          48.1
     reluctant          13            12     25       0.3         0.3          48.0
          loud          24            22     46       0.6         0.5          47.8
     emotional          46            41     87       1.1         1.0          47.1
        humble          18            16     34       0.4         0.4          47.1
    passionate          26            23     49       0.6         0.5          46.9
         naive          29            25     54       0.7         0.6          46.3
   intelligent          76            65    141       1.9         1.5          46.1
   responsible          69            58    127       1.7         1.4          45.7
      reliable          24            20     44       0.6         0.5          45.5
          nice          35            29     64       0.9         0.7          45.3
    supportive          17            14     31       0.4         0.3          45.2
         crazy          19            15     34       0.5         0.4          44.1
         stoic          28            22     50       0.7         0.5          44.0
        fierce          18            14     32       0.4         0.3          43.8
          weak          86            66    152       2.1         1.6          43.4
      talented          62            47    109       1.5         1.1          43.1
     talkative          12             9     21       0.3         0.2          42.9
          lazy          34            25     59       0.8         0.6          42.4
         cruel          35            25     60       0.9         0.6          41.7
       selfish          26            18     44       0.6         0.4          40.9
  enthusiastic          19            13     32       0.5         0.3          40.6
     perverted          59            40     99       1.5         0.9          40.4
       skilled         149            99    248       3.7         2.3          39.9
    protective          55            36     91       1.4         0.9          39.6
          cool          75            49    124       1.9         1.2          39.5
short-tempered          14             9     23       0.3         0.2          39.1
       serious         149            92    241       3.7         2.2          38.2
      powerful         185           111    296       4.6         2.6          37.5
          calm         145            87    232       3.6         2.1          37.5
           mad          25            15     40       0.6         0.4          37.5
      carefree          42            25     67       1.0         0.6          37.3
          wild          32            19     51       0.8         0.4          37.3
     impulsive          22            13     35       0.5         0.3          37.1
     oblivious          22            13     35       0.5         0.3          37.1
     observant          17            10     27       0.4         0.2          37.0
    thoughtful          17            10     27       0.4         0.2          37.0
       awkward          24            14     38       0.6         0.3          36.8
  level-headed          14             8     22       0.3         0.2          36.4
      peaceful          21            12     33       0.5         0.3          36.4
      reckless          18            10     28       0.4         0.2          35.7
          rude          31            17     48       0.8         0.4          35.4
      arrogant          62            31     93       1.5         0.7          33.3
     laid-back          18             9     27       0.4         0.2          33.3
  good-natured          16             8     24       0.4         0.2          33.3
      ruthless          36            18     54       0.9         0.4          33.3
         loyal         103            46    149       2.6         1.1          30.9
     eccentric          36            16     52       0.9         0.4          30.8
       logical          18             8     26       0.4         0.2          30.8
       trusted          23            10     33       0.6         0.2          30.3
       cynical          19             8     27       0.5         0.2          29.6
        direct          38            16     54       0.9         0.4          29.6
   charismatic          30            12     42       0.7         0.3          28.6
    successful          31            12     43       0.8         0.3          27.9
     easygoing          25             8     33       0.6         0.2          24.2
      cowardly          16             4     20       0.4         0.1          20.0

In [70]:
# Score = skew * log(count) — rewards both extremes and volume
import numpy as np

trait_df["male_skew"] = 100 - trait_df["female_share"]  # higher = more male
trait_df["female_skew"] = trait_df["female_share"]       # higher = more female

trait_df["male_score"] = trait_df["male_skew"] * np.log(trait_df["total"])
trait_df["female_score"] = trait_df["female_skew"] * np.log(trait_df["total"])

print("Top male-skewed (skew + volume):")
print(trait_df.nlargest(10, "male_score")[["trait", "total", "female_share", "male_score"]].to_string(index=False))

print("\nTop female-skewed (skew + volume):")
print(trait_df.nlargest(10, "female_score")[["trait", "total", "female_share", "female_score"]].to_string(index=False))

Top male-skewed (skew + volume):
   trait  total  female_share  male_score
powerful    296          37.5  355.647466
   loyal    149          30.9  345.772690
    calm    232          37.5  340.421086
 serious    241          38.2  338.960450
 skilled    248          39.9  331.357068
  strong    503          48.1  322.848630
arrogant     93          33.3  302.324386
    cool    124          39.5  291.627035
    kind    459          53.6  284.387930
    weak    152          43.4  284.351637

Top female-skewed (skew + volume):
    trait  total  female_share  female_score
      shy    227          74.0    401.446301
beautiful    229          73.8    401.008684
 tsundere     60          88.3    361.530625
 cheerful    179          68.7    356.373405
   clumsy     76          80.3    347.757887
energetic    116          71.6    340.357058
   mature    119          70.6    337.406119
    sweet    126          69.0    333.703452
     kind    459          53.6    328.517091
tomboyish     32          90.6    313.995673